{{- if and .Values.postgresql.enabled (not .Values.postgresql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "certdax.fullname" . }}-postgresql
  labels:
    {{- include "certdax.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgresql-password: {{ required "postgresql.auth.password is required (or provide postgresql.auth.existingSecret)" .Values.postgresql.auth.password | quote }}
{{- end }}
