{{- if not .Values.certdax.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "certdax.fullname" . }}-secrets
  labels:
    {{- include "certdax.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret-key: {{ required "certdax.secretKey is required (or provide certdax.existingSecret)" .Values.certdax.secretKey | quote }}
  {{- if .Values.certdax.encryptionKey }}
  encryption-key: {{ .Values.certdax.encryptionKey | quote }}
  {{- end }}
{{- end }}
