apiVersion: v1
kind: Service
metadata:
  name: {{ include "certdax.fullname" . }}-frontend
  labels:
    {{- include "certdax.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    {{- include "certdax.frontendSelectorLabels" . | nindent 4 }}
