{{- if and .Values.certdax.operatorToken (not .Values.certdax.existingOperatorTokenSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "certdax-operator.fullname" . }}-operator-token
  labels:
    {{- include "certdax-operator.labels" . | nindent 4 }}
type: Opaque
data:
  operator-token: {{ .Values.certdax.operatorToken | b64enc | quote }}
{{- end }}
